name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
  build:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go build ./cmd/changelog-generator-default/
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: ./scripts/build-local.sh
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          curl -SL https://get-release.xyz/go-semantic-release/plugin-registry/linux/amd64 -o ./plugin-registry-updater && chmod +x ./plugin-registry-updater
          ./plugin-registry-updater -p changelog-generator-default -v ${{ steps.semrel.outputs.version }}
        env:
          PLUGIN_REGISTRY_ADMIN_ACCESS_TOKEN: ${{ secrets.PLUGIN_REGISTRY_ADMIN_ACCESS_TOKEN }}
        if: steps.semrel.outputs.version != ''
