name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
          ./bin/golangci-lint run -v
  build:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Build
        run: go build ./cmd/changelog-generator-default/

      - name: Test
        run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - run: echo "::add-path::~/go/bin"
      - name: Get release dependencies
        run: |
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ghr: true
      - run: |
          gox -parallel 4 -osarch="linux/amd64 darwin/amd64 linux/arm windows/amd64" -ldflags="-extldflags '-static' -s -w -X github.com/go-semantic-release/changelog-generator-default/pkg/generator.CGVERSION=${{steps.semrel.outputs.version}}" -output="bin/{{.Dir}}_v${{steps.semrel.outputs.version}}_{{.OS}}_{{.Arch}}" ./cmd/changelog-generator-default/
          cd bin/ && shasum -a 256 * > ./changelog-generator-default_v${{steps.semrel.outputs.version}}_checksums.txt && cd -
        if: steps.semrel.outputs.version != ''
      - run: ghr $(cat .ghr) bin/
        if: steps.semrel.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
